### ISSUE TITLE
Add initial unit tests

### ISSUE THREAD

**Issue by andrewebdev** [peppelinux/django-audit#10]

**Comment by peppelinux** [comment]
Related to
https://github.com/peppelinux/django-audit-wazuh/issues/9

**Comment by peppelinux** [comment]
Please do PR to dev branch,
I'm going to plan a release schedule and policy and a periodic pypi package release

thank to you

**Comment by andrewebdev** [comment]
What python versions are we targeting @peppelinux ? 3.4 and up?

**Comment by peppelinux** [comment]
3.5 and up

**Comment by peppelinux** [comment]
https://github.com/peppelinux/django-audit-wazuh/pull/14
