### ISSUE TITLE
Old style Middleware replacement

### ISSUE THREAD

**Issue by andrewebdev** [peppelinux/django-audit#12]
Currently the midddleware is constructed in a way that supports pre django 1.2.

I'm of the opinion that we should move to the new-style middleware and only support the versions of django that still receive security updates.

Would this be acceptable change @peppelinux ?

**Comment by peppelinux** [comment]
Right

**Comment by peppelinux** [comment]
https://github.com/peppelinux/django-audit-wazuh/pull/14
