### ISSUE TITLE
Possible typo `logging` vs `logger`

### ISSUE THREAD

**Issue by andrewebdev** [peppelinux/django-audit#13]
https://github.com/peppelinux/django-audit-wazuh/blob/7a9de577a999521b6ee576a6f898cb358889dbb0/auditing/middlewares.py#L67

Is the above line intentionally `logging` instead of `logger`?

**Comment by peppelinux** [comment]
Typo errore, include this in your pending PR of you can 👍

**Comment by peppelinux** [comment]
https://github.com/peppelinux/django-audit-wazuh/pull/14
