### ISSUE TITLE
PYPI version is old

### ISSUE THREAD

**Issue by andrewebdev** [peppelinux/django-audit#16]
Just noticed that the version on PYPI is old, published Apr 2020. The last update we did was on Oct 2020

**Comment by peppelinux** [comment]
thank you @andrewebdev 
my fault!

https://github.com/peppelinux/django-audit-wazuh/commit/a9fdb7003477e8aa1e141f2ad94c075d2ba905c2
https://pypi.org/project/django-audit-wazuh/
