### ISSUE TITLE
Django-audit already exists on pypi and is for mongodb

### ISSUE THREAD

**Issue by andrewebdev** [peppelinux/django-audit#2]
Have a slight issue setting up the wazuh configuration for this.

The readme doesn't specify clearly enough whether I need to add the decodes/rules on my manager or on my agents. This may be apparent to the more experienced wazuh user, but I'm still very new to wazuh so a tiny bit of guidance may be welcome to newcomers like myself.

**Comment by peppelinux** [comment]
Hi Andre,
feel free to put any additional informations in the README, I'd be happy to merge your contributions.
Wazuh propagates these definitions from master to agents, I configured as an example the django agents group for guidance.
That's a Wazuh convention, documented in its official documentation

**Comment by andrewebdev** [comment]
Ah ok thx. I wasn't aware of that. Ok that makes more sense then. I'll need to study the docs in a bit more detail then.
