### ISSUE TITLE
Log output for headers can lead to invalid JSON

### ISSUE THREAD

**Issue by andrewebdev** [peppelinux/django-audit#3]
https://github.com/peppelinux/django-audit-wazuh/blob/37ee8b3f517cccd6a4c86b1cd17975e3b6edef19/auditing/middlewares.py#L52

Building up the JSON for headers in this way can lead to invalid JSON output. If any of the header field values have double quote in them (which they do for one of my javascript modules), then the double quotes are just entered as is, and cuases the json value to close prematurely and thus be invalid. Below is a example of such a header:

```
"Fetch-Fragments": ".top-bar-title,#pageContent,#mainOverlay [slot="content"]",
```

As you can see the `[slot="content"]` will cause the json value to close soon as it sees the double quote.

**Comment by peppelinux** [comment]
Hi andrew,

It's something not covered yet, so thank you for issuing this.
The patch would be this:

````
head_items = ['"{}": "{}"'.format(*[i.replace('"', '\\"') for i in hea]) for hea in response_headers]
````

Please do a test and let me know, if it works you can do a PR with this, I'll appreciate

**Comment by andrewebdev** [comment]
Is there a particular reason this is manually formatted as a json, rather than building up a python dict and using `json.dumps()`?
If feels like it would make the code more readable and would avoid edge cases like this. Creating a single `.replace()` for every edge case (like other escape characters) could become quite cumbersome?

**Comment by peppelinux** [comment]
I agree, I wait  a PR from you if you prefer

**Comment by peppelinux** [comment]
and more, @andrewebdev fill free to enjoy in it as mantainer of this repository. I'd really appreciate your support in this!

**Comment by andrewebdev** [comment]
Yup I was going to do a PR myself, just working on some other issues also.
