### ISSUE TITLE
Going forward

### ISSUE THREAD

**Issue by andrewebdev** [peppelinux/django-audit#7]
Regarding your request for maintainer. I cannot dedicate a lot of time to be an active maintainer. Right now I'm just adding and updating things as I need them in some of my projects.

I'm happy to be a contributor, there is a lot that I'm planning to change on my own forked branch based on our project needs, which I can contribute back.

I'm just not in the right position to have the responsibility of maintainer at this time.

**Comment by peppelinux** [comment]
All your contributions are appreciated, really thanks
