### ISSUE TITLE
Use django-ipware for consistent and DRY method to retrieve request source IP

### ISSUE THREAD

**Issue by andrewebdev** [peppelinux/django-audit#8]
django-ipware provides a consistent method to retrieve the source IP from the request. Since we use it in many projects it would be useful to use this library to retrieve IP's.

I suggest to add the import with `try..except ImportError` block. This way it's not a hard dependency, but if the user has the library installed, it will default to that library. We can then keep the manual method as a fallback.

I can take care of this if it's accepted.

**Comment by peppelinux** [comment]
I will, good idea

**Comment by peppelinux** [comment]
Please do PR to dev branch

**Comment by peppelinux** [comment]
https://github.com/peppelinux/django-audit-wazuh/pull/14
