### ISSUE TITLE
Refactor log message construction

### ISSUE THREAD

**Issue by andrewebdev** [peppelinux/django-audit#9]
Currently log messages are compiled by manually building up strings that will _eventually_ form part of a larger JSON message.

This introduces many places where a slight spelling mistake or variable containing invalid json text could break the JSON output. I had one case where, on a error regarding POST variable for "username", caused the json message to contain, no comma between some of the fields.

My suggestion here is to use a python dictionary whenever we are compiling the "parts" of the message. This makes it a lot easier to update key values within the dict.

Before we write the log message, we can then use `json.dumps()` to get a valid json string, and strip the `{` and `}` from the start and end of the json string. This can then be inserted into the logging message as it's currently done.

I can take care of this if accepted

**Comment by peppelinux** [comment]
LGTM but we haven't yet  a coverage of the code through unit tests.
I think that important changes like this should be coupled with good, autoimated and reproducibile, tests.
Would you implement also a django stadard test for this feature?

**Comment by andrewebdev** [comment]
:+1:

**Comment by peppelinux** [comment]
Please do PR to dev branch

**Comment by peppelinux** [comment]
https://github.com/peppelinux/django-audit-wazuh/pull/14
